import type { CharacterDefinition } from '../sprite_types';

/** Oso pardo con ushanka y balalaika. */
export const BEAR: CharacterDefinition = {
  id: 'bear',
  colors: {
    H: '#6b6f7d',
    h: '#8d93a3',
    S: '#8a5a32',
    A: '#d9b38c',
    K: '#1b1b22',
    T: '#8a5a32',
    R: '#8a5a32',
    P: '#8a5a32',
    B: '#4a2e18',
    X: '#d9883b',
    Y: '#5a3418',
  },
  head: [
    '..HHHHHHHH..',
    '.HHhhhhhhHH.',
    'HHHHHHHHHHHH',
    'HHSSSSSSSSHH',
    'HHSKSSSSKSHH',
    'HHSSAAAASSHH',
    'HH.SAKKAS.HH',
    'HH.SAAAAS.HH',
    '....SSSS....',
  ],
  torso: [
    '.SSSSSSSSSS.',
    'SSSSAAAASSSS',
    'SSSAAAAAASSS',
    'SSSAAAAAASSS',
    'SSSAAAAAASSS',
    'SSSAAAAAASSS',
    'SSSSAAAASSSS',
    'SSSSSSSSSSSS',
    '.SSSSSSSSSS.',
  ],
  chestProp: [
    '........YY',
    '.......YY.',
    '......YY..',
    '.....YY...',
    '..XXYX....',
    '.XXXXX....',
    'XXXKXX....',
    'XXXXXX....',
  ],
};
