/** Textos de la interfaz (en español). */
export const TEXTS = {
  title: 'ТЕТРИС',
  pressAnyKey: 'PULSA CUALQUIER TECLA',
  menu: {
    start: 'INICIAR JUEGO',
    startLevel: 'NIVEL INICIAL',
    music: 'MÚSICA',
    celebrations: 'CELEBRACIONES',
    controls: 'CONTROLES',
    records: 'RÉCORDS',
    on: 'ACTIVADA',
    off: 'DESACTIVADA',
    onPlural: 'ACTIVADAS',
    offPlural: 'DESACTIVADAS',
    hint: '↑ ↓ ELEGIR · ← → CAMBIAR · ENTER ACEPTAR',
  },
  controls: {
    title: 'CONTROLES',
    rows: [
      ['← →', 'MOVER'],
      ['↓', 'BAJAR (SOFT DROP)'],
      ['↑', 'ROTAR EN SENTIDO HORARIO'],
      ['Z', 'ROTAR EN SENTIDO ANTIHORARIO'],
      ['P', 'PAUSA'],
      ['M', 'SILENCIAR / ACTIVAR SONIDO'],
      ['ESC', 'VOLVER AL MENÚ'],
      ['ENTER', 'EMPEZAR / REINICIAR'],
      ['BOTÓN PILOTO', 'EL JUEGO JUEGA SOLO'],
    ],
  },
  records: {
    title: 'RÉCORDS',
    empty: 'TODAVÍA NO HAY RÉCORDS',
    rank: '#',
    score: 'PUNTOS',
    lines: 'LÍNEAS',
    level: 'NIVEL',
    date: 'FECHA',
  },
  back: 'ESC VOLVER',
  hud: {
    score: 'PUNTUACIÓN',
    best: 'RÉCORD',
    lines: 'LÍNEAS',
    level: 'NIVEL',
    next: 'SIGUIENTE',
    nextHidden: 'OCULTA',
    goal: 'OBJETIVO',
    muted: 'SONIDO SILENCIADO (M)',
  },
  autopilot: {
    off: 'PILOTO AUTOMÁTICO: NO',
    on: 'PILOTO AUTOMÁTICO: SÍ',
  },
  pause: {
    title: 'PAUSA',
    hint: 'P CONTINUAR · ESC MENÚ',
  },
  celebration: {
    levelUp: (level: number): string => `¡NIVEL ${level}!`,
    skip: 'ENTER / ESPACIO SALTAR',
  },
  gameOver: {
    title: 'FIN DE LA PARTIDA',
    newRecord: '¡NUEVO RÉCORD!',
    ranked: 'ENTRA EN EL TOP 10',
    autopilotUsed: 'PARTIDA CON PILOTO AUTOMÁTICO: NO CUENTA PARA RÉCORDS',
    hintRestart: 'ENTER JUGAR DE NUEVO',
    hintMenu: 'ESC MENÚ',
  },
} as const;
